# Generated by Django 5.2.4 on 2025-07-16 22:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_purchaseorders_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitems",
            old_name="expexted_shipping_date",
            new_name="expected_shipping_date",
        ),
        migrations.RemoveField(
            model_name="purchaseorders",
            name="id",
        ),
        migrations.AddField(
            model_name="purchaseorders",
            name="order_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Scheduled", "Scheduled"),
                    ("Delivered", "Delievered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
    ]
