# Generated by Django 5.2.4 on 2025-07-21 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0003_rename_expexted_shipping_date_orderitems_expected_shipping_date_and_more",
        ),
        ("products", "0002_alter_productphotos_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseorderitems",
            old_name="expexted_shipping_date",
            new_name="expected_shipping_date",
        ),
        migrations.RemoveField(
            model_name="purchaseorders",
            name="order_amount",
        ),
        migrations.RemoveField(
            model_name="salesorders",
            name="order_amount",
        ),
        migrations.AddField(
            model_name="purchaseorderitems",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="products.products",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="actual_shipping_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderitems",
            name="actual_shipping_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderitems",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Scheduled", "Scheduled"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorders",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Scheduled", "Scheduled"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
    ]
