# Generated by Django 5.2.4 on 2025-07-16 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raw_materials", "0002_alter_rawmaterialpricehistory_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billofmaterials",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="billofmaterials",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
