# Generated by Django 5.2.4 on 2025-07-22 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_productphotos_updated_at_and_more"),
        ("raw_materials", "0003_billofmaterials_created_at_and_more"),
        ("suppliers", "0002_alter_suppliers_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billofmaterials",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="bill_of_materials",
                to="products.products",
            ),
        ),
        migrations.AlterField(
            model_name="billofmaterials",
            name="raw_material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="bill_of_materials",
                to="raw_materials.rawmaterials",
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterialpricehistory",
            name="raw_material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="price_history",
                to="raw_materials.rawmaterials",
            ),
        ),
        migrations.AlterField(
            model_name="rawmaterials",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="raw_materials",
                to="suppliers.suppliers",
            ),
        ),
    ]
