# Generated by Django 5.2.4 on 2025-07-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productphotos",
            name="photo_url",
            field=models.URLField(max_length=300),
        ),
    ]
