# Generated by Django 5.2.4 on 2025-07-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productphotos",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
