# Generated by Django 5.2.4 on 2025-07-16 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_alter_timeentries_break_end_time_and_more"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="assigend_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="task_assigned_by",
                to="employees.employees",
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="assigend_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="task_assigned_to",
                to="employees.employees",
            ),
        ),
    ]
