# Generated by Django 5.2.4 on 2025-07-17 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_tasks_assigend_by_alter_tasks_assigend_to"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="assigend_by",
            new_name="assigned_by",
        ),
        migrations.RenameField(
            model_name="tasks",
            old_name="assigend_to",
            new_name="assigned_to",
        ),
    ]
