# Generated by Django 5.2.4 on 2025-07-22 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_rename_assigend_by_tasks_assigned_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasks",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
