# Generated by Django 5.2.4 on 2025-07-16 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0001_initial"),
        ("inventory", "0002_alter_inventory_updated_at"),
        ("products", "0002_alter_productphotos_updated_at_and_more"),
        ("raw_materials", "0003_billofmaterials_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="product",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="raw_material",
        ),
        migrations.AlterModelOptions(
            name="inventory",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="type",
        ),
        migrations.AddField(
            model_name="inventory",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="ProductInventory",
            fields=[
                (
                    "inventory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="inventory.inventory",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="products.products",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("inventory.inventory",),
        ),
        migrations.CreateModel(
            name="RawMaterialInventory",
            fields=[
                (
                    "inventory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="inventory.inventory",
                    ),
                ),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="raw_materials.rawmaterials",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("inventory.inventory",),
        ),
    ]
