import type { InventoryItem } from "@/types/types";

const mockInventoryData: InventoryItem[] = [
  {
    id: 1,
    product_id: 101,
    name: "Wireless Ergonomic Mouse",
    quantity: 150,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 2,
    product_id: 102,
    name: "Mechanical Gaming Keyboard",
    quantity: 75,
    location: "Warehouse B",
    status: "In Stock",
  },
  {
    id: 3,
    product_id: 103,
    name: "27-inch 4K Monitor",
    quantity: 30,
    location: "Store Front",
    status: "Low Stock",
  },
  {
    id: 4,
    product_id: 104,
    name: "USB-C Hub (7-in-1)",
    quantity: 200,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 5,
    product_id: 105,
    name: "Portable SSD 1TB",
    quantity: 90,
    location: "Warehouse B",
    status: "In Stock",
  },
  {
    id: 6,
    product_id: 106,
    name: "Noise-Cancelling Headphones",
    quantity: 45,
    location: "Store Front",
    status: "In Stock",
  },
  {
    id: 7,
    product_id: 107,
    name: "Webcam 1080p",
    quantity: 120,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 8,
    product_id: 108,
    name: "Gaming Laptop (High-End)",
    quantity: 10,
    location: "Store Front",
    status: "Low Stock",
  },
  {
    id: 9,
    product_id: 109,
    name: "External Hard Drive 4TB",
    quantity: 60,
    location: "Warehouse B",
    status: "In Stock",
  },
  {
    id: 10,
    product_id: 110,
    name: "Smartphone Tripod Stand",
    quantity: 250,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 11,
    product_id: 111,
    name: "Bluetooth Speaker (Compact)",
    quantity: 180,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 12,
    product_id: 112,
    name: "Smartwatch (Fitness Edition)",
    quantity: 35,
    location: "Store Front",
    status: "In Stock",
  },
  {
    id: 13,
    product_id: 113,
    name: "Drone with 4K Camera",
    quantity: 5,
    location: "Store Front",
    status: "Low Stock",
  },
  {
    id: 14,
    product_id: 114,
    name: "VR Headset (Entry Level)",
    quantity: 8,
    location: "Store Front",
    status: "Low Stock",
  },
  {
    id: 15,
    product_id: 115,
    name: "Graphic Design Tablet",
    quantity: 20,
    location: "Warehouse B",
    status: "In Stock",
  },
  {
    id: 16,
    product_id: 116,
    name: "Desk Chair (Ergonomic)",
    quantity: 15,
    location: "Warehouse B",
    status: "Low Stock",
  },
  {
    id: 17,
    product_id: 117,
    name: "LED Desk Lamp (Dimmable)",
    quantity: 100,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 18,
    product_id: 118,
    name: "Portable Projector",
    quantity: 12,
    location: "Store Front",
    status: "In Stock",
  },
  {
    id: 19,
    product_id: 119,
    name: "Smart Home Hub",
    quantity: 25,
    location: "Warehouse B",
    status: "In Stock",
  },
  {
    id: 20,
    product_id: 120,
    name: "Robot Vacuum Cleaner",
    quantity: 7,
    location: "Store Front",
    status: "Low Stock",
  },
  {
    id: 21,
    product_id: 121,
    name: "Electric Kettle (Smart)",
    quantity: 40,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 22,
    product_id: 122,
    name: "Air Fryer (Large Capacity)",
    quantity: 22,
    location: "Warehouse B",
    status: "In Stock",
  },
  {
    id: 23,
    product_id: 123,
    name: "Blender (High-Speed)",
    quantity: 18,
    location: "Store Front",
    status: "In Stock",
  },
  {
    id: 24,
    product_id: 124,
    name: "Coffee Maker (Espresso)",
    quantity: 9,
    location: "Store Front",
    status: "Low Stock",
  },
  {
    id: 25,
    product_id: 125,
    name: "Digital Kitchen Scale",
    quantity: 70,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 26,
    product_id: 126,
    name: "Fitness Tracker Band",
    quantity: 55,
    location: "Warehouse B",
    status: "In Stock",
  },
  {
    id: 27,
    product_id: 127,
    name: "Yoga Mat (Anti-Slip)",
    quantity: 80,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 28,
    product_id: 128,
    name: "Resistance Band Set",
    quantity: 110,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 29,
    product_id: 129,
    name: "Dumbbell Set (Adjustable)",
    quantity: 6,
    location: "Store Front",
    status: "Low Stock",
  },
  {
    id: 30,
    product_id: 130,
    name: "Jump Rope (Weighted)",
    quantity: 95,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 31,
    product_id: 131,
    name: "Electric Toothbrush (Sonic)",
    quantity: 30,
    location: "Warehouse B",
    status: "In Stock",
  },
  {
    id: 32,
    product_id: 132,
    name: "Water Flosser",
    quantity: 28,
    location: "Warehouse B",
    status: "In Stock",
  },
  {
    id: 33,
    product_id: 133,
    name: "Smart Bathroom Scale",
    quantity: 15,
    location: "Store Front",
    status: "Low Stock",
  },
  {
    id: 34,
    product_id: 134,
    name: "Hair Dryer (Ionic)",
    quantity: 20,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 35,
    product_id: 135,
    name: "Straightener (Ceramic)",
    quantity: 18,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 36,
    product_id: 136,
    name: "Portable Fan (Rechargeable)",
    quantity: 65,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 37,
    product_id: 137,
    name: "Humidifier (Ultrasonic)",
    quantity: 25,
    location: "Warehouse B",
    status: "In Stock",
  },
  {
    id: 38,
    product_id: 138,
    name: "Air Purifier (HEPA)",
    quantity: 10,
    location: "Store Front",
    status: "Low Stock",
  },
  {
    id: 39,
    product_id: 139,
    name: "Dehumidifier (Compact)",
    quantity: 8,
    location: "Store Front",
    status: "Low Stock",
  },
  {
    id: 40,
    product_id: 140,
    name: "Smart Lighting Kit",
    quantity: 40,
    location: "Warehouse B",
    status: "In Stock",
  },
  {
    id: 41,
    product_id: 141,
    name: "Security Camera (Outdoor)",
    quantity: 15,
    location: "Warehouse B",
    status: "Low Stock",
  },
  {
    id: 42,
    product_id: 142,
    name: "Video Doorbell (Wireless)",
    quantity: 5,
    location: "Store Front",
    status: "Out of Stock",
  },
  {
    id: 43,
    product_id: 143,
    name: "Smart Thermostat",
    quantity: 12,
    location: "Store Front",
    status: "In Stock",
  },
  {
    id: 44,
    product_id: 144,
    name: "Laptop Stand (Adjustable)",
    quantity: 50,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 45,
    product_id: 145,
    name: "Monitor Arm (Dual)",
    quantity: 20,
    location: "Warehouse B",
    status: "In Stock",
  },
  {
    id: 46,
    product_id: 146,
    name: "Ergonomic Foot Rest",
    quantity: 35,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 47,
    product_id: 147,
    name: "Cable Management Sleeves",
    quantity: 100,
    location: "Warehouse A",
    status: "In Stock",
  },
  {
    id: 48,
    product_id: 148,
    name: 'Portable Monitor 15.6"',
    quantity: 10,
    location: "Store Front",
    status: "Low Stock",
  },
  {
    id: 49,
    product_id: 149,
    name: "USB Microphone (Condenser)",
    quantity: 25,
    location: "Warehouse B",
    status: "In Stock",
  },
  {
    id: 50,
    product_id: 150,
    name: "LED Ring Light",
    quantity: 30,
    location: "Warehouse B",
    status: "In Stock",
  },
  {
    id: 51,
    product_id: 151,
    name: "Mini Projector",
    quantity: 3,
    location: "Store Front",
    status: "Out of Stock",
  },
  {
    id: 52,
    product_id: 152,
    name: "Smart Plugs (4-pack)",
    quantity: 60,
    location: "Warehouse A",
    status: "In Stock",
  },
];

export default mockInventoryData;
