import type { OrderItem } from "@/types/types"; // Assuming OrderItem is defined in your types file

export const mockOrderItems: OrderItem[] = [
  {
    id: 1,
    customer_id: 1001,
    shop_name: "Sakura Mart",
    address: "1-1-1 Main St, Tokyo",
    order_value: "¥1250.75",
    status: "Scheduled",
  },
  {
    id: 2,
    customer_id: 1002,
    shop_name: "Blue Ocean Groceries",
    address: "2-3-4 Central Ave, Osaka",
    order_value: "¥540.20",
    status: "Out for Delivery",
  },
  {
    id: 3,
    customer_id: 1003,
    shop_name: "Tech World Electronics",
    address: "5-6-7 Park Rd, Kyoto",
    order_value: "¥8999.00",
    status: "Delivered",
  },
  {
    id: 4,
    customer_id: 1004,
    shop_name: "Fashion Hub Boutique",
    address: "8-9-0 Riverwalk, Nagoya",
    order_value: "¥3200.50",
    status: "Not Scheduled",
  },
  {
    id: 5,
    customer_id: 1005,
    shop_name: "Green Leaf Cafe",
    address: "10-11-12 Hilltop, Fukuoka",
    order_value: "¥750.00",
    status: "Scheduled",
  },
  {
    id: 6,
    customer_id: 1006,
    shop_name: "Urban Books",
    address: "13-14-15 Ocean Blvd, Yokohama",
    order_value: "¥1800.99",
    status: "Out for Delivery",
  },
  {
    id: 7,
    customer_id: 1007,
    shop_name: "Hardware Haven",
    address: "16-17-18 Old Town, Sapporo",
    order_value: "¥4500.25",
    status: "Delivered",
  },
  {
    id: 8,
    customer_id: 1008,
    shop_name: "Pet Paradise",
    address: "19-20-21 Mountain View, Kobe",
    order_value: "¥2100.00",
    status: "Not Scheduled",
  },
  {
    id: 9,
    customer_id: 1009,
    shop_name: "Gourmet Delight",
    address: "22-23-24 Cherry Blossom Lane, Hiroshima",
    order_value: "¥980.50",
    status: "Scheduled",
  },
  {
    id: 10,
    customer_id: 1010,
    shop_name: "Quick Stop Convenience",
    address: "25-26-27 Seaside Drive, Okinawa",
    order_value: "¥300.15",
    status: "Out for Delivery",
  },
  {
    id: 11,
    customer_id: 1011,
    shop_name: "Sakura Mart",
    address: "2-3-4 Central Ave, Osaka",
    order_value: "¥1500.00",
    status: "Delivered",
  },
  {
    id: 12,
    customer_id: 1012,
    shop_name: "Tech World Electronics",
    address: "1-1-1 Main St, Tokyo",
    order_value: "¥7500.00",
    status: "Not Scheduled",
  },
  {
    id: 13,
    customer_id: 1013,
    shop_name: "Green Leaf Cafe",
    address: "8-9-0 Riverwalk, Nagoya",
    order_value: "¥620.00",
    status: "Scheduled",
  },
  {
    id: 14,
    customer_id: 1014,
    shop_name: "Fashion Hub Boutique",
    address: "5-6-7 Park Rd, Kyoto",
    order_value: "¥2800.75",
    status: "Out for Delivery",
  },
  {
    id: 15,
    customer_id: 1015,
    shop_name: "Pet Paradise",
    address: "13-14-15 Ocean Blvd, Yokohama",
    order_value: "¥1950.00",
    status: "Delivered",
  },
  {
    id: 16,
    customer_id: 1016,
    shop_name: "Urban Books",
    address: "10-11-12 Hilltop, Fukuoka",
    order_value: "¥950.50",
    status: "Not Scheduled",
  },
  {
    id: 17,
    customer_id: 1017,
    shop_name: "Gourmet Delight",
    address: "19-20-21 Mountain View, Kobe",
    order_value: "¥1100.00",
    status: "Scheduled",
  },
  {
    id: 18,
    customer_id: 1018,
    shop_name: "Hardware Haven",
    address: "22-23-24 Cherry Blossom Lane, Hiroshima",
    order_value: "¥3800.00",
    status: "Out for Delivery",
  },
  {
    id: 19,
    customer_id: 1019,
    shop_name: "Quick Stop Convenience",
    address: "16-17-18 Old Town, Sapporo",
    order_value: "¥250.00",
    status: "Delivered",
  },
  {
    id: 20,
    customer_id: 1020,
    shop_name: "Blue Ocean Groceries",
    address: "25-26-27 Seaside Drive, Okinawa",
    order_value: "¥670.30",
    status: "Not Scheduled",
  },
  {
    id: 21,
    customer_id: 1021,
    shop_name: "Sakura Mart",
    address: "5-6-7 Park Rd, Kyoto",
    order_value: "¥1300.00",
    status: "Scheduled",
  },
  {
    id: 22,
    customer_id: 1022,
    shop_name: "Tech World Electronics",
    address: "8-9-0 Riverwalk, Nagoya",
    order_value: "¥9500.00",
    status: "Out for Delivery",
  },
  {
    id: 23,
    customer_id: 1023,
    shop_name: "Green Leaf Cafe",
    address: "1-1-1 Main St, Tokyo",
    order_value: "¥580.00",
    status: "Delivered",
  },
  {
    id: 24,
    customer_id: 1024,
    shop_name: "Fashion Hub Boutique",
    address: "2-3-4 Central Ave, Osaka",
    order_value: "¥3500.00",
    status: "Not Scheduled",
  },
  {
    id: 25,
    customer_id: 1025,
    shop_name: "Pet Paradise",
    address: "16-17-18 Old Town, Sapporo",
    order_value: "¥2200.00",
    status: "Scheduled",
  },
  {
    id: 26,
    customer_id: 1026,
    shop_name: "Urban Books",
    address: "19-20-21 Mountain View, Kobe",
    order_value: "¥1050.00",
    status: "Out for Delivery",
  },
  {
    id: 27,
    customer_id: 1027,
    shop_name: "Gourmet Delight",
    address: "10-11-12 Hilltop, Fukuoka",
    order_value: "¥1200.00",
    status: "Delivered",
  },
  {
    id: 28,
    customer_id: 1028,
    shop_name: "Hardware Haven",
    address: "13-14-15 Ocean Blvd, Yokohama",
    order_value: "¥4100.00",
    status: "Not Scheduled",
  },
  {
    id: 29,
    customer_id: 1029,
    shop_name: "Quick Stop Convenience",
    address: "22-23-24 Cherry Blossom Lane, Hiroshima",
    order_value: "¥320.00",
    status: "Scheduled",
  },
  {
    id: 30,
    customer_id: 1030,
    shop_name: "Blue Ocean Groceries",
    address: "25-26-27 Seaside Drive, Okinawa",
    order_value: "¥700.00",
    status: "Out for Delivery",
  },
  {
    id: 31,
    customer_id: 1031,
    shop_name: "Sakura Mart",
    address: "8-9-0 Riverwalk, Nagoya",
    order_value: "¥1400.00",
    status: "Delivered",
  },
  {
    id: 32,
    customer_id: 1032,
    shop_name: "Tech World Electronics",
    address: "5-6-7 Park Rd, Kyoto",
    order_value: "¥8200.00",
    status: "Not Scheduled",
  },
  {
    id: 33,
    customer_id: 1033,
    shop_name: "Green Leaf Cafe",
    address: "2-3-4 Central Ave, Osaka",
    order_value: "¥650.00",
    status: "Scheduled",
  },
  {
    id: 34,
    customer_id: 1034,
    shop_name: "Fashion Hub Boutique",
    address: "1-1-1 Main St, Tokyo",
    order_value: "¥3000.00",
    status: "Out for Delivery",
  },
  {
    id: 35,
    customer_id: 1035,
    shop_name: "Pet Paradise",
    address: "25-26-27 Seaside Drive, Okinawa",
    order_value: "¥2050.00",
    status: "Delivered",
  },
  {
    id: 36,
    customer_id: 1036,
    shop_name: "Urban Books",
    address: "22-23-24 Cherry Blossom Lane, Hiroshima",
    order_value: "¥900.00",
    status: "Not Scheduled",
  },
  {
    id: 37,
    customer_id: 1037,
    shop_name: "Gourmet Delight",
    address: "16-17-18 Old Town, Sapporo",
    order_value: "¥1150.00",
    status: "Scheduled",
  },
  {
    id: 38,
    customer_id: 1038,
    shop_name: "Hardware Haven",
    address: "13-14-15 Ocean Blvd, Yokohama",
    order_value: "¥4300.00",
    status: "Out for Delivery",
  },
  {
    id: 39,
    customer_id: 1039,
    shop_name: "Quick Stop Convenience",
    address: "10-11-12 Hilltop, Fukuoka",
    order_value: "¥280.00",
    status: "Delivered",
  },
  {
    id: 40,
    customer_id: 1040,
    shop_name: "Blue Ocean Groceries",
    address: "19-20-21 Mountain View, Kobe",
    order_value: "¥720.00",
    status: "Not Scheduled",
  },
  {
    id: 41,
    customer_id: 1041,
    shop_name: "Sakura Mart",
    address: "1-1-1 Main St, Tokyo",
    order_value: "¥1280.00",
    status: "Scheduled",
  },
  {
    id: 42,
    customer_id: 1042,
    shop_name: "Tech World Electronics",
    address: "2-3-4 Central Ave, Osaka",
    order_value: "¥8500.00",
    status: "Out for Delivery",
  },
  {
    id: 43,
    customer_id: 1043,
    shop_name: "Green Leaf Cafe",
    address: "5-6-7 Park Rd, Kyoto",
    order_value: "¥600.00",
    status: "Delivered",
  },
  {
    id: 44,
    customer_id: 1044,
    shop_name: "Fashion Hub Boutique",
    address: "8-9-0 Riverwalk, Nagoya",
    order_value: "¥3100.00",
    status: "Not Scheduled",
  },
  {
    id: 45,
    customer_id: 1045,
    shop_name: "Pet Paradise",
    address: "10-11-12 Hilltop, Fukuoka",
    order_value: "¥2150.00",
    status: "Scheduled",
  },
  {
    id: 46,
    customer_id: 1046,
    shop_name: "Urban Books",
    address: "13-14-15 Ocean Blvd, Yokohama",
    order_value: "¥1000.00",
    status: "Out for Delivery",
  },
  {
    id: 47,
    customer_id: 1047,
    shop_name: "Gourmet Delight",
    address: "16-17-18 Old Town, Sapporo",
    order_value: "¥1220.00",
    status: "Delivered",
  },
  {
    id: 48,
    customer_id: 1048,
    shop_name: "Hardware Haven",
    address: "19-20-21 Mountain View, Kobe",
    order_value: "¥4000.00",
    status: "Not Scheduled",
  },
  {
    id: 49,
    customer_id: 1049,
    shop_name: "Quick Stop Convenience",
    address: "22-23-24 Cherry Blossom Lane, Hiroshima",
    order_value: "¥310.00",
    status: "Scheduled",
  },
  {
    id: 50,
    customer_id: 1050,
    shop_name: "Blue Ocean Groceries",
    address: "25-26-27 Seaside Drive, Okinawa",
    order_value: "¥690.00",
    status: "Out for Delivery",
  },
];
