# Generated by Django 5.2.4 on 2025-07-16 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hire_date", models.DateTimeField()),
                ("job_title", models.CharField(max_length=100)),
                ("salary_per_hr", models.DecimalField(decimal_places=2, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="users",
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeEntries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("break_start_time", models.DateTimeField()),
                ("break_end_time", models.DateTimeField()),
                ("notes", models.CharField(max_length=300)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Regular", "Regular"),
                            ("Overtime", "Overtime"),
                            ("Sick", "Sick"),
                            ("Paid Leave", "Paid Leave"),
                            ("Unpaid Leave", "Unpaid Leave"),
                        ],
                        default="Regular",
                        max_length=20,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="employees.employees",
                    ),
                ),
            ],
        ),
    ]
