# Generated by Django 5.2.4 on 2025-07-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_employees_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentries",
            name="break_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timeentries",
            name="break_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
