# Generated by Django 5.2.4 on 2025-07-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_alter_timeentries_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentries",
            name="notes",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
